export const packingListTemplates = {
  weekend: [
    { itemName: "T-Shirts", itemQuantity: 3 },
    { itemName: "Shorts", itemQuantity: 2 },
    { itemName: "Underwear", itemQuantity: 2 },
    { itemName: "Toothbrush and Toothpaste", itemQuantity: 1 },
    { itemName: "Shampoo and Body Wash", itemQuantity: 1 },
    { itemName: "Phone Charger", itemQuantity: 1 },
    { itemName: "Prescription Medications", itemQuantity: 1 },
  ],
  "one week": [
    { itemName: "T-Shirts", itemQuantity: 7 },
    { itemName: "Pants/Jeans", itemQuantity: 3 },
    { itemName: "Socks", itemQuantity: 7 },
    { itemName: "Underwear", itemQuantity: 7 },
    { itemName: "Toiletries Kit", itemQuantity: 1 },
    { itemName: "Phone Charger", itemQuantity: 1 },
    { itemName: "Prescription Medications", itemQuantity: 1 },
  ],
  "two weeks": [
    { itemName: "T-Shirts", itemQuantity: 14 },
    { itemName: "Pants/Jeans", itemQuantity: 5 },
    { itemName: "Shorts", itemQuantity: 3 },
    { itemName: "Socks", itemQuantity: 14 },
    { itemName: "Underwear", itemQuantity: 14 },
    { itemName: "Toiletries Kit", itemQuantity: 1 },
    { itemName: "Phone Charger", itemQuantity: 1 },
    { itemName: "Prescription Medications", itemQuantity: 2 },
    { itemName: "Camera and Accessories", itemQuantity: 1 },
  ],
  "three weeks": [
    { itemName: "T-Shirts", itemQuantity: 21 },
    { itemName: "Pants/Jeans", itemQuantity: 7 },
    { itemName: "Shorts", itemQuantity: 5 },
    { itemName: "Socks", itemQuantity: 21 },
    { itemName: "Underwear", itemQuantity: 21 },
    { itemName: "Toiletries Kit", itemQuantity: 1 },
    { itemName: "Phone Charger", itemQuantity: 1 },
    { itemName: "Prescription Medications", itemQuantity: 2 },
    { itemName: "Camera and Accessories", itemQuantity: 1 },
    { itemName: "Books/Magazines", itemQuantity: 1 },
  ],
};
